"""update properties to json

Revision ID: 3949499e7a56
Revises: f734665c837e
Create Date: 2026-01-17 15:35:10.061962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3949499e7a56'
down_revision: Union[str, Sequence[str], None] = 'f734665c837e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_properties_event_id'), table_name='event_properties')
    op.drop_table('event_properties')
    op.add_column('events', sa.Column('properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'properties')
    op.create_table('event_properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), nullable=True),
    sa.Column('failure_reason', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_properties_event_id'), 'event_properties', ['event_id'], unique=1)
    # ### end Alembic commands ###
