"""create initial tables

Revision ID: f734665c837e
Revises: 
Create Date: 2026-01-17 00:59:04.539820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f734665c837e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('event_properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_properties_event_id'), 'event_properties', ['event_id'], unique=True)
    op.create_table('send_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_send_requests_event_id'), 'send_requests', ['event_id'], unique=False)
    op.create_index(op.f('ix_send_requests_template_name'), 'send_requests', ['template_name'], unique=False)
    op.create_index(op.f('ix_send_requests_user_id'), 'send_requests', ['user_id'], unique=False)
    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=64), nullable=False),
    sa.Column('suppression_reason', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppressions_event_id'), 'suppressions', ['event_id'], unique=False)
    op.create_index(op.f('ix_suppressions_template_name'), 'suppressions', ['template_name'], unique=False)
    op.create_index(op.f('ix_suppressions_user_id'), 'suppressions', ['user_id'], unique=False)
    op.create_table('user_traits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=True),
    sa.Column('risk_segment', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_traits_event_id'), 'user_traits', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_traits_event_id'), table_name='user_traits')
    op.drop_table('user_traits')
    op.drop_index(op.f('ix_suppressions_user_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_template_name'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_event_id'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_send_requests_user_id'), table_name='send_requests')
    op.drop_index(op.f('ix_send_requests_template_name'), table_name='send_requests')
    op.drop_index(op.f('ix_send_requests_event_id'), table_name='send_requests')
    op.drop_table('send_requests')
    op.drop_index(op.f('ix_event_properties_event_id'), table_name='event_properties')
    op.drop_table('event_properties')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
